set -g default-terminal "${TERM}"
set -g status off
# if it does not work, try
set -g mouse on
# setw -g mouse on 

bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# Mac
set -s copy-command 'pbcopy'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
